### ISSUE TITLE
Support for regexp or custom resolver for the modules

### ISSUE THREAD

**Issue by chicoxyzzy** [MilanKovacic/vite-plugin-externalize-dependencies#65]
Hi. Thank you for the plugin. It would be great if RegExp or a custom resolver (`resolve(id) { return id.startsWith('prefix-') }`) could be a valid `externals` parameter)

**Comment by MilanKovacic** [comment]
Hi, I will implement this functionality, supporting both RegEx, and custom resolver, in a similar way to rollup/webpack:

"Either a function that takes an id and returns true (external) or false (not external), or an Array of module IDs, or regular expressions to match module IDs, that should remain external to the bundle."

**Comment by MilanKovacic** [comment]
I have added the functionality in https://github.com/MilanKovacic/vite-plugin-externalize-dependencies/pull/77. I still need to add some tests, and do a bit of refactoring (was busy).
Plugin will now support externalizing via module name, custom function, or RegEx. I have also aligned the behavior with other bundlers so that externalizing for example "react", will also externalize the sub-exports like "react/jsx-runtime".

Feel free to give it a test :)

**Comment by MilanKovacic** [comment]
Released in 0.11.0.

**Comment by chicoxyzzy** [comment]
Thank you, @MilanKovacic, for creating the plugin. It's working flawlessly! We have used it as a reference in our [blog post](https://socketsupply.co/blog/live-reload/) to guide our users. They have tried it out and are very pleased with the results. Big thanks!

**Comment by MilanKovacic** [comment]
No problem. I am glad it helped your users :)
